image_width: 1920
image_height: 1080
camera_name: pt_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [855.33201,   0.     , 903.57711,
           0.     , 856.29466, 551.89933,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.218814, 0.033484, 0.003526, 0.001334, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [568.80532,   0.     , 921.62301,   0.     ,
           0.     , 769.71932, 560.63822,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
